export const GET_ALL_BUSES = "GET_ALL_BUSES"
export const SEARCH_ROUTES = "SEARCH_ROUTES"
export const GET_SINGLE_BUS = "GET_SINGLE_BUSES"
export const GET_ALL_ROUTES = "GET_ALL_ROUTES"

// CE 12371269